version: "3.8"
services:
  web:
    build: .
    image: registry.dis.cwi.nl/vr2gather-orchestrator-v2
    restart: always
    ports:
      - "8090:8090"
    command: yarn start
    logging:
      options:
        max-size: "200k"
        max-file: "3"
