services:
  web:
    build: .
    image: registry.dis.cwi.nl/vr2gather-orchestrator-v2
    restart: always
    environment:
      - PORT=8090
      - LOG_LEVEL=debug
    volumes:
      - ./config/:/code/config
      - ./.env:/code/.env
    ports:
      - "8090:8090"
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "8095:8095"
      - "8096:8096"
      - "8097:8097"
      - "8098:8098"
      - "8099:8099"
      - "9000-9999/udp"
    command: yarn start
    logging:
      options:
        max-size: "200k"
        max-file: "3"
