services:
  web:
    build: .
    image: registry.dis.cwi.nl/vr2gather-orchestrator-v2
    restart: always
    environment:
      - PORT=8090
      - LOG_LEVEL=debug
    volumes:
      - ./config/:/code/config
      - ./.env:/code/.env
    ports:
      - "8090-8099:8090-8099"
      - "9000-9100:9000-9100/udp"
    command: yarn start
    logging:
      options:
        max-size: "200k"
        max-file: "3"
