services:
  web:
    build: .
    image: registry.dis.cwi.nl/vr2gather-orchestrator-v2
    restart: always
    environment:
      - PORT=8090
      - LOG_LEVEL=debug
    ports:
      - "8090:8090"
      - "8094:8094"
      - "8095:8095"
    command: yarn start
    logging:
      options:
        max-size: "200k"
        max-file: "3"
